name: Publish to AUR
on:
  release:
    types: [released]
jobs:
  Publish-to-AUR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Get latest release"
        id: latestrelease
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
      - name: "Update PKGVER in PKGBUILD"
        run: sed -i '/pkgver=/s/$/'$(echo '${{ steps.latestrelease.outputs.tag_name }}' |  sed 's/v//g')'/' AUR/PKGBUILD
      - run: cp AUR/PKGBUILD .
      - name: "Update PKGBUILD Checksums and generate SRCINFO"
        uses: datakrama/archlinux-package-action@v1.0.3
        with: 
          updpkgsums: true
          srcinfo: true
          namcap: false
          flags: ''
      - run: cat PKGBUILD
      - run: cat .SRCINFO
      - name: "Push to AUR"
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: emusak-bin
          pkgbuild: PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to ${{ steps.latestrelease.outputs.tag_name }}
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
